services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mygallery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: jollywitch/mygallery:latest
    volumes:
      - ./media:/app/media
      - ./config.json:/app/config.json
    ports:
      - "5353:5353"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db

volumes:
  postgres_data: